disabled_rules:
    - nesting
    - trailing_comma
opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - array_init
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - expiring_todo
    - explicit_init
    - file_header
    - file_name
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_default_parameter_at_end
    - identical_operands
    - implicitly_unwrapped_optional
    - indentation_width
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - let_var_whitespace
    - literal_expression_end_indentation
    - local_doc_comment
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - no_extension_access_modifier
    - nslocalizedstring_key
    - number_separator
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - prohibited_super_call
    - raw_value_for_camel_cased_codable_enum
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - return_value_from_void_function
    - self_binding
    - shorthand_optional_binding
    - sorted_first_last
    - static_operator
    - toggle_bool
    - trailing_closure
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - weak_delegate
    - yoda_condition

excluded:
    - Tests/SwiftPackageListCoreTests/Resources

analyzer_rules:
    - unused_declaration
    - unused_import

identifier_name:
    allowed_symbols:
        - '_'
    excluded:
        - x
        - y

indentation_width:
    include_compiler_directives: false

line_length:
    warning: 130
    error: 200
    ignores_urls: true

trailing_whitespace:
    ignores_empty_lines: true

type_name:
    allowed_symbols:
        - '_'
